services:
  - type: web
    name: shift-calendar-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: |
      echo "Using Python version: $(python --version)"
      pip install --no-build-isolation -r requirements.txt
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
